workflows:
  android-build:
    name: JinocaFlix Android APK
    max_build_duration: 60
    
    environment:
      flutter: stable
      java: 17
      
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true

    scripts:
      - name: Atualizar arquitetura do Android (v1 para v2)
        script: |
          echo "Deletando pasta velha..."
          rm -rf android
          echo "Criando pasta nova atualizada..."
          flutter create --platforms android .
          
      - name: Configurar Android (MinSDK e Internet)
        script: |
          echo "Ajustando o SDK do player de video..."
          if [ -f "android/app/build.gradle.kts" ]; then
            sed -i.bak 's/flutter.minSdkVersion/21/g' android/app/build.gradle.kts
          elif [ -f "android/app/build.gradle" ]; then
            sed -i.bak 's/flutter.minSdkVersion/21/g' android/app/build.gradle
          fi
          
          echo "Injetando Permissao de Internet no Manifest..."
          perl -pi -e 's/<application/<uses-permission android:name="android.permission.INTERNET"\/>\n    <application/g' android/app/src/main/AndroidManifest.xml
          
      - name: Baixar pacotes
        script: flutter pub get

      - name: Aplicar Vacinas no Cache (Bypass AGP 8 e Flutter 3.3+)
        script: |
          echo "Vacinando o Namespace..."
          find ~/.pub-cache/hosted -path "*/better_player-*/android/build.gradle" -exec perl -pi -e 's/android \{/android {\n    namespace "com.jhomlala.better_player"/g' {} \;
          find ~/.pub-cache/hosted -path "*/wakelock-*/android/build.gradle" -exec perl -pi -e 's/android \{/android {\n    namespace "creativecreatorormaybenot.wakelock"/g' {} \;
          
          echo "Vacinando a funcao hashValues morta do Flutter..."
          find ~/.pub-cache/hosted/pub.dev/better_player-* -name "*.dart" -exec perl -pi -e 's/hashValues\(/Object.hash\(/g' {} \;

      - name: Compilar o APK em modo Release
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
