workflows:
  android-build:
    name: JinocaFlix Android APK
    max_build_duration: 60
    
    environment:
      flutter: stable
      java: 17
      
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true

    scripts:
      - name: Baixar pacotes (Pub get)
        script: flutter pub get

      - name: Compilar o APK em modo Release
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
